### ISSUE TITLE
태진 번호를 기준으로 금영의 번호를 받아오는 기능 추가 요청

### ISSUE THREAD

**Issue by ongoz** [JangChulwoon/KaraokeParsing#1]
안녕하세요 `노래노트` 개발자입니다.
기존 노래방 파싱 api는 잘 사용하고있습니다 :)

이번에 개발 진행중인 노래노트 2.0에서 필요한 중요 기능에 대한 api기능 추가를 요청드립니다.
현재 태진/금영에 대한 노래를 각자 요청해서 데이터를 받아오고있는데,
태진, 금영 정보를 각각 받아오다보니 api호출이 중복으로 일어나는 문제가 있습니다.

태진과 금영의 노래 정보가 100%일치하는게 아니기에 정보를 강제로 merge할 수는 없지만
한쪽의 노래 정보를 기반으로 다른 노래방 업체의 정보 중 일치하는 정보를 가져오는 부분을 제안하고자 합니다.
검색결과에 대해 모두 적용할 경우에는 처리해야 할 양이나 필요하지 않은 리소스를 너무 많이 사용하는것 같아서
현재 프로젝트에서 내부적으로 처리하고 있는 `태진 노래방 번호를 기준으로 금영 노래방 번호를 받아오는 기능`만 먼저 구현이 되었으면 합니다.

`예시형식`
type : TJ / KY
number : 62349

**Comment by JangChulwoon** [comment]
추가하도록 하겠습니다 !
